# Generated by Django 5.0.3 on 2024-03-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationform_app', '0002_userdetails_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='user_type',
            field=models.CharField(blank=True, choices=[('User', 'User'), ('Admin', 'Admin')], max_length=20, null=True),
        ),
    ]
