# Generated by Django 5.0.3 on 2024-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrationform_app', '0004_userdetails_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='otp',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='bln_verified',
            field=models.BooleanField(default=False),
        ),
    ]
